terraform {
  required_version = ">= 0.12"
}

variable "machine_cidr" {
  type = string

  description = <<EOF
The IP address space from which to assign machine IPs.
Default "10.0.0.0/16"
EOF
  default = "10.0.0.0/16"
}

variable "base_domain" {
  type = string

  description = <<EOF
The base DNS domain of the cluster. It must NOT contain a trailing period. Some
DNS providers will automatically add this if necessary.

Example: `openshift.example.com`.

Note: This field MUST be set manually prior to creating the cluster.
This applies only to cloud platforms.
EOF

}

variable "clustername" {
  type = string

  description = <<EOF
The name of the cluster. It must NOT contain a trailing period. Some
DNS providers will automatically add this if necessary.

Note: This field MUST be set manually prior to creating the cluster.
EOF

}

// This variable is generated by OpenShift internally. Do not modify
variable "cluster_id" {
  type = string

  description = <<EOF
(internal) The OpenShift cluster id.

This cluster id must be of max length 27 and must have only alphanumeric or hyphen characters.
EOF

}

variable "use_ipv4" {
  type = bool
  default = true
  description = <<EOF
Should the cluster be created with ipv4 networking. (default = true)
EOF

}

variable "use_ipv6" {
  type = bool
  default = false
  description = <<EOF
Should the cluster be created with ipv6 networking. (default = false)
EOF

}
